### PR TITLE
Add the compress layout

### PR DESCRIPTION
**Pull request by doktorbro**
Based on your [tweet](https://twitter.com/robertwilliam_s/status/545636707480371200) I help you to compress HTML.

### CODE REVIEW

**Comment by rbrtsmith** [comment]
What does this offer over gzip compression? or is it something that can be used to remove whitespace to fix the spacing issue with inline-blocks?  Thanks!

**Comment by doktorbro** [comment]
This reduces the raw file size.

**Comment by doktorbro** [comment]
@rbrtsmith Do you need more information on this?

**Comment by rbrtsmith** [comment]
To be honest I haven't had the time to fully look into this yet, I will
read up on it when I get a free moment.  Need to fully understand how this
works before I'd be happy to put it live.

I'll try to check it out over the next few weeks.

Thanks!

On 7 February 2015 at 13:55, Anatol Broder notifications@github.com wrote:

> @rbrtsmith https://github.com/rbrtsmith Do you need more information on
> this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rbrtsmith/rbrtsmith.github.io/pull/1#issuecomment-73363197
> .

## 

Kind regards,

_Robert Smith_

---

_W_: www.rwmsithdesigns.com
_T_: +46(0)72586-4166
_E_: rbrtsmith@googlemail.com

**Pull request closed without merging**
